### ISSUE TITLE
Add v1.0.0 version tag so packagist sees this as stable

### ISSUE THREAD

**Issue by hashworks** [nfauchelle/PhergieKeepAlive#3]
``` sh
git tag -a v1.0.0
git push --tags
```

Then update Packagist if you didn't link GitHub & Packagist.

**Comment by hashworks** [comment]
Afterwards you should also change the README.md to the following:

## Install

To install via [Composer](http://getcomposer.org/), use the command below, it will automatically detect the latest version and bind it with `~`.

```
composer require nfauchelle/phergie-keep-alive
```

See Phergie documentation for more information on
[installing and enabling plugins](https://github.com/phergie/phergie-irc-bot-react/wiki/Usage#plugins).

**Comment by nfauchelle** [comment]
Sorted now
