### ISSUE TITLE
composer.json suggestion in README.md is wrong

### ISSUE THREAD

**Issue by hashworks** [nfauchelle/PhergieKeepAlive#4]
``` JSON
{
    "require": {
        "nfauchelle\PhergieKeepAlive": "dev-master"
    }
}
```

Firstly, it's not valid JSON - `/` instead of `\`.
Secondly, the composer.json requires the name on packagist: `"nfauchelle/phergie-keep-alive"`.

**Comment by hashworks** [comment]
Note that this becomes obsolete when you follow my advice in #3.

**Comment by nfauchelle** [comment]
This is sorted :)
